### ISSUE TITLE
build from source issues 

### ISSUE THREAD

**Issue by omershlo** [ligeroinc/LigeroRSA#10]
I recently tried to build the project from the instructions given in the README doc. I started with a clean AWS machine. Here are the issues I encountered so far: 
- The instruction specify Ubuntu 14.04 however the docker uses 18.04. In fact, before trying 18.04 I tried 16.04 and couldn't manage to complete (specifically because glibc for 16.04 is not updated)
- To install gcc-8, a specific ppa should be added first: 
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
```
- the line `sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 700 --slave /usr/bin/g++ g++ /usr/bin/g++-7
update-alternatives:` produces an error: 
`error: alternative path /usr/bin/gcc-7 doesn't exist`
- running `cd aws_scripts && ./native_build.sh: ` produces multiple errors: 
```
mkdir: cannot create directory ‘AWS/Registered_IPs’: No such file or directory
mkdir: cannot create directory ‘AWS/Registered_Private_IPs’: No such file or directory
mkdir: cannot create directory ‘AWS/Registered_Instances’: No such file or directory
./native_build.sh: line 14: cmake: command not found
./native_build.sh: line 15: cd: src: No such file or directory
./native_build.sh: line 16: make: command not found
```
I don't know how to treat the AWS files (would love to get clarification). 
To solve the Cmake issue, there should be some instruction to install `make` and Cmake should be added to the path.
- ` fatal error: cryptopp/files.h: No such file or directory  ` . To solve you should instruct to install `crypto++` and to add it to the path of the compiler. 
- zmq errors: looks like the 4.3 version in `/depends` folder is missing some stuff needed for transport layer. To solve I downloaded 4.4 and replaced it in `/depends`
- I got this error during `make`: 
```
[ 84%] Built target validator
virtual memory exhausted: Cannot allocate memory
```
   I have a machine with storage of 8GB. To resolve, I added 500GB. My conclusions: 
1) There should probably be different requirements for running a party and running a coordinator.
2) Requirements should be made more explicit  

- `Error: cc1plus: out of memory allocating 65536 bytes after a total of 1854951424 bytes`. I was running with 8GB RAM. I beefed up my machine with 700GB RAM and got it to work.  My comments in the bullet above are relevant here as well. 

- When trying to run a simple 1 party example (using 1 coordinator, 1 party and 1 verifier as per instructions : `./build/src/coordinator_full_protocol --parties 1`). I get the following error on the party side (the coordinator terminate): 
```
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error
Aborted (core dumped)
```

**Comment by tarikriviere** [comment]
Thank you Omer for the detailed message; very helpful and appreciated. 

**Ubuntu version:** Indeed, the official version should have been updated to 18.04 in the readme. This will be rectified promptly. 

**native_build.sh** the first three lines can be ignored, they are a remnant of a staging environment that is not used here. (this will also be rectified shortly). The cryptopp dependency will also be addressed shortly (updating CMakeLists.txt). Lastly, we do have as a default a parallelized build, but that can strain resources indeed so for simplicity we will just revert to sequential, which will remove this problem when you try to build on a limited spec machine.

**zmq** we haven't been able to reproduce yet but will investigate and revert promptly

**simulations** indeed we will provide suggested hardware settings for various experiment scales. On a separate note, the minimum number of parties to run an experiment should actually be 2. We will explicitly mention it in the readme and handle it at the coordinator level to prevent user attempting a run with one party only.

**Comment by tarikriviere** [comment]
This item slated for closing on the next code review [08/04]
