### ISSUE TITLE
All but one candidate are dropped in Round 11

### ISSUE THREAD

**Issue by khovratovich** [ligeroinc/LigeroRSA#15]
https://github.com/ligeroinc/LigeroRSA/blob/15a5950db39fbdfe9f95de382c4602dc5a2e5fd7/include/EncryptedClient.hpp#L794-L798

If Coordinator later replies with discardFlags array bigger than 1 element, the program aborts. Is this reduction really needed?

**Comment by ligeroinc** [comment]
This reduction is needed because we only prove correctness of at most one candidate via zkp. We made this choice to save on communication and computational effort.

**Comment by ligeroinc** [comment]
Yes, it is safe to assume that.
