### ISSUE TITLE
Possible array lengths mismatch

### ISSUE THREAD

**Issue by khovratovich** [ligeroinc/LigeroRSA#18]
https://github.com/ligeroinc/LigeroRSA/blob/15a5950db39fbdfe9f95de382c4602dc5a2e5fd7/include/EncryptedClient.hpp#L2856-L2859

`ax_shares ` has size `primesGCD`, whereas `rc` reaches to `alphasGCD.size()*candidates.size()`. If there are more than 1 candidate, the memory will be corrupted.

**Comment by khovratovich** [comment]
Is this reduction to 1 candidate a part of the specification or just a local optimization? If not a reduction then `assert` should be there

**Comment by tarikriviere** [comment]
This item slated for closing on the next code review [08/04]
