### ISSUE TITLE
Actual constraint not given

### ISSUE THREAD

**Issue by khovratovich** [ligeroinc/LigeroRSA#26]
https://github.com/ligeroinc/LigeroRSA/blob/15a5950db39fbdfe9f95de382c4602dc5a2e5fd7/include/protocol/ExpressNPStatement.hpp#L1304

**Comment by khovratovich** [comment]
The same for `addEquation8`, `addEquation11`, etc. up to `addEquation14`

**Comment by tarikriviere** [comment]
Note that this was handled as part of the response to #29.
