### ISSUE TITLE
Data structures are not documented

### ISSUE THREAD

**Issue by khovratovich** [ligeroinc/LigeroRSA#28]
- [ ] [intraBlocReferences ](https://github.com/ligeroinc/LigeroRSA/blob/05717dcf21122bb06a16e43859a4e37d49bd9385/include/protocol/ExpressNPStatement.hpp#L14)
- [ ] [Statements](https://github.com/ligeroinc/LigeroRSA/blob/15a5950db39fbdfe9f95de382c4602dc5a2e5fd7/include/protocol/ExpressNPStatement.hpp#L20)
- [ ] [ExpressNPStatement](https://github.com/ligeroinc/LigeroRSA/blob/15a5950db39fbdfe9f95de382c4602dc5a2e5fd7/include/protocol/ExpressNPStatement.hpp#L104-L144)

**Comment by tarikriviere** [comment]
All documentation added; as usual this will be reflected in the next public repo update
