### ISSUE TITLE
Functions are not documented

### ISSUE THREAD

**Issue by khovratovich** [ligeroinc/LigeroRSA#29]
-[ ] [Preprocessing](https://github.com/ligeroinc/LigeroRSA/blob/15a5950db39fbdfe9f95de382c4602dc5a2e5fd7/include/protocol/ExpressNPStatement.hpp#L288)
-[ ] [NP_RSACeremony_Bounding_Variables](https://github.com/ligeroinc/LigeroRSA/blob/15a5950db39fbdfe9f95de382c4602dc5a2e5fd7/include/protocol/ExpressNPStatement.hpp#L332)
-[ ] [NP_Equate_Variables](https://github.com/ligeroinc/LigeroRSA/blob/15a5950db39fbdfe9f95de382c4602dc5a2e5fd7/include/protocol/ExpressNPStatement.hpp#L428)
-[ ] [NP_Connecting_Proofs](https://github.com/ligeroinc/LigeroRSA/blob/15a5950db39fbdfe9f95de382c4602dc5a2e5fd7/include/protocol/ExpressNPStatement.hpp#L890)
-[ ] [addIntegrityTestMinusFinalMod](https://github.com/ligeroinc/LigeroRSA/blob/15a5950db39fbdfe9f95de382c4602dc5a2e5fd7/include/protocol/ExpressNPStatement.hpp#L2990)

It is clear that the following functions add constraints but the logic is unclear:

-[ ] [addEquationR7](https://github.com/ligeroinc/LigeroRSA/blob/15a5950db39fbdfe9f95de382c4602dc5a2e5fd7/include/protocol/ExpressNPStatement.hpp#L1304)
-[ ] [addEquationR8](https://github.com/ligeroinc/LigeroRSA/blob/15a5950db39fbdfe9f95de382c4602dc5a2e5fd7/include/protocol/ExpressNPStatement.hpp#L1505)
-[ ] [addEquation11](https://github.com/ligeroinc/LigeroRSA/blob/15a5950db39fbdfe9f95de382c4602dc5a2e5fd7/include/protocol/ExpressNPStatement.hpp#L1815)
-[ ] [addEquation12](https://github.com/ligeroinc/LigeroRSA/blob/15a5950db39fbdfe9f95de382c4602dc5a2e5fd7/include/protocol/ExpressNPStatement.hpp#L2160)
-[ ] [addEquation13](https://github.com/ligeroinc/LigeroRSA/blob/15a5950db39fbdfe9f95de382c4602dc5a2e5fd7/include/protocol/ExpressNPStatement.hpp#L2462)

**Comment by tarikriviere** [comment]
1) addIntegrityTestMinusFinalMod is deprecated and was removed
2) documentation for all other functions has been added/supplemented

all changes will be reflected in the next public repo update

**Comment by tarikriviere** [comment]
3. Detailed notes have now been added for all the addEquation functions above.

Again, this will be reflected in the next public repo update.
