### ISSUE TITLE
Zero-Knowledge questions for call July 7th

### ISSUE THREAD

**Issue by khovratovich** [ligeroinc/LigeroRSA#32]
1. What is the flow of proof preparation in the code? Current understanding is that
- a witness is constructed in `gatherData`. The private part is `SecretData`, there is no other private part. All the public parts are filled now as well.
- (d,s,e) from `gatherData` goes to `prover`. The latter does not take anything else from client or another party.
- prover creates constraints round by round in `buildConstraintSet`.
- (this in unclear) constraints and witness go to the Ligero module to create a proof
- proofs are collected by Coordinator and passed to Verifier. Along with something? 

2. It seems that for constraints for the range proofs are build in two steps, once bounds are collected, and then all the constraints are created for some array of ranges. Is this for all such constraints? Is there any other proof part constructed this way?

3. Constraints up to round 6 are more or less clear but later I am lost. We need some documentation for them.

4. Can we abstract the Ligero API out? Is it possible to have a list of functions which are Ligero- but not Diogenes-specific? 

5. There are several places where the witness values are copied or transformed by NTT. Where are constraints that enforce this? And how are they built?

6. Does Verifier construct the statement in exactly the same way? How (if at all) does he use with signed parts of transcript?

7. How do we check  that `earlyCommitment` matches the final committed values?

**Comment by omershlo** [comment]
8. why is this [`else`](https://github.com/ligeroinc/LigeroRSA/blob/05717dcf21122bb06a16e43859a4e37d49bd9385/include/protocol/ExpressNPStatement.hpp#L557) statement needed? 

9.  what is `generateAndCommitRandomness` ?(the spec v_4 line 357 points to such a function but we couldn't find it)

10. please go over `run_round` for the prover and verifier. would be nice if you could sketch the structure of these functions 

11. explain `calculateRTAStitchingMatrix` and how it relates to the stitching describe in the spec  ? 

12. Please detail all places where bounding constraints are added. 

13.  function [`NP_statement`](https://github.com/ligeroinc/LigeroRSA/blob/05717dcf21122bb06a16e43859a4e37d49bd9385/include/protocol/ExpressNPStatement.hpp#L578) seems a bit not up to date  . Can you explain this function and what changes needs to be made to update it ?

14. why [this](https://github.com/ligeroinc/LigeroRSA/blob/15a5950db39fbdfe9f95de382c4602dc5a2e5fd7/src/party_full_protocol.cpp#L280-#L281) mod q_i is needed?
