### ISSUE TITLE
Questions on the NP statement construction

### ISSUE THREAD

**Issue by khovratovich** [ligeroinc/LigeroRSA#34]
1. `addBoundingConstraint(*,x,C,*)` creates two variables to store `x` and `x+C` and one constraint. It stores references to these variables and values in a separate array. It returns the reference to `x` variable. Constraints for separate bits of these values and linking their sums to `x` and `x+C` happens  later in `NP_RSACeremony_Bounding_Variables`. Is this correct?  

2. `addSplitVariable(x)` allocates variable(s) for `x` and returns a reference to the array. Is this correct?

3. Can you point to some place in the code which relates the early witness with the later witness, concretely establishing a constraint?

4. Both `addEquation1` and `addEquation2` use `u_x`, but how are the variables related? The reference to `u_x` variable is stored in `_uxBlocs` in `addEquation1`, but `addEquation2` does not seem to use it.

5. The same for `u_z` in `addEquation3` and `addEquation4`.

6. The same for `yi` in `addEquation3` and `addEquation4`.

7. The same for `siP` in `addEquation5` and `addKeyGenPolyEval`.

8. In the first call, `addEquationR7` creates and returns references to variables that correspond to {B_c'},{x_tc} (spec page 17). Is this correct?

9. What is the role of `miscBlocIdx` and `miscBloc` in `addEquationR8`, `addEquation11`, `addEquation12`?

10. No new variable in `addEquation13` is stored as a reference. However, we reuse `x_sharesPS`, `y_sharesPS`, which were stored in other functions.

11. `q_p_prod_r11`, `q_q_prod_r11`, `sigmaxGCD`, `r_CRTs` are used in different constraints but are never stored.

**Comment by tarikriviere** [comment]
Addressed on 08/04 and marked for closing on 08/18.
