### ISSUE TITLE
commit 15a5950 details 

### ISSUE THREAD

**Issue by omershlo** [ligeroinc/LigeroRSA#8]
It is a bit hard to understand what exactly changed. 
Can you provide some more detailed changelog please? 
<img width="551" alt="Screen Shot 2020-05-29 at 8 42 05" src="https://user-images.githubusercontent.com/2446179/83225466-8065c980-a188-11ea-95e3-e061749b8eb1.png">

**Comment by tarikriviere** [comment]
Indeed, the initial few commits on this repo were very lumpy. Should be more manageable going forward. In the interim, these are the main changes in this commit:

1. Added missing cmake/FindCryptoPP.cmake file for crypto++ integration
2. Removed deprecated code tied to original implementation of ZKP for sigma protocol
3. Added further doxygen-compatible documentation for functions
4. Added Signatures
5. Corrected ZKP bounding for decryption noise R
6. Removed deprecated files (original FFT, benchmark key gen etc.)
7. Added malicious party that deliberately corrupts ZKP inputs at random
8. Formatting changes for consistency

**Comment by tarikriviere** [comment]
This item slated for closing on the next code review [08/04]
